//
// Protocol Buffer message types for the sequencer.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: sequencer/messages/defs.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrevBlockHash []byte      `protobuf:"bytes,1,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	Body          *SequenceTx `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Sig           []byte      `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	Height        int64       `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *Block) GetBody() *SequenceTx {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Block) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *Block) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SequenceTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    []byte             `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Data    []byte             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Sig     []byte             `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	Nonce   []byte             `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Expires []*ExpiryCondition `protobuf:"bytes,20,rep,name=expires,proto3" json:"expires,omitempty"`
}

func (x *SequenceTx) Reset() {
	*x = SequenceTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SequenceTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceTx) ProtoMessage() {}

func (x *SequenceTx) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceTx.ProtoReflect.Descriptor instead.
func (*SequenceTx) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{1}
}

func (x *SequenceTx) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *SequenceTx) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SequenceTx) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *SequenceTx) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *SequenceTx) GetExpires() []*ExpiryCondition {
	if x != nil {
		return x.Expires
	}
	return nil
}

type ExpiryCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Condition:
	//	*ExpiryCondition_Unix
	Condition isExpiryCondition_Condition `protobuf_oneof:"condition"`
}

func (x *ExpiryCondition) Reset() {
	*x = ExpiryCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpiryCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiryCondition) ProtoMessage() {}

func (x *ExpiryCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiryCondition.ProtoReflect.Descriptor instead.
func (*ExpiryCondition) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{2}
}

func (m *ExpiryCondition) GetCondition() isExpiryCondition_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (x *ExpiryCondition) GetUnix() *UNIXExpiryCondition {
	if x, ok := x.GetCondition().(*ExpiryCondition_Unix); ok {
		return x.Unix
	}
	return nil
}

type isExpiryCondition_Condition interface {
	isExpiryCondition_Condition()
}

type ExpiryCondition_Unix struct {
	Unix *UNIXExpiryCondition `protobuf:"bytes,1,opt,name=unix,proto3,oneof"`
}

func (*ExpiryCondition_Unix) isExpiryCondition_Condition() {}

type UNIXExpiryCondition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *UNIXExpiryCondition) Reset() {
	*x = UNIXExpiryCondition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UNIXExpiryCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNIXExpiryCondition) ProtoMessage() {}

func (x *UNIXExpiryCondition) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNIXExpiryCondition.ProtoReflect.Descriptor instead.
func (*UNIXExpiryCondition) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{3}
}

func (x *UNIXExpiryCondition) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type GetTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From uint64        `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   uint64        `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Txs  []*SequenceTx `protobuf:"bytes,3,rep,name=txs,proto3" json:"txs,omitempty"`
}

func (x *GetTransactions) Reset() {
	*x = GetTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactions) ProtoMessage() {}

func (x *GetTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactions.ProtoReflect.Descriptor instead.
func (*GetTransactions) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactions) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *GetTransactions) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *GetTransactions) GetTxs() []*SequenceTx {
	if x != nil {
		return x.Txs
	}
	return nil
}

type GetSequencerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetSequencerInfo) Reset() {
	*x = GetSequencerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSequencerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSequencerInfo) ProtoMessage() {}

func (x *GetSequencerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSequencerInfo.ProtoReflect.Descriptor instead.
func (*GetSequencerInfo) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{5}
}

func (x *GetSequencerInfo) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SequencerPrimaryAdvertisement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiaddress []byte `protobuf:"bytes,1,opt,name=multiaddress,proto3" json:"multiaddress,omitempty"`
}

func (x *SequencerPrimaryAdvertisement) Reset() {
	*x = SequencerPrimaryAdvertisement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SequencerPrimaryAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequencerPrimaryAdvertisement) ProtoMessage() {}

func (x *SequencerPrimaryAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequencerPrimaryAdvertisement.ProtoReflect.Descriptor instead.
func (*SequencerPrimaryAdvertisement) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{6}
}

func (x *SequencerPrimaryAdvertisement) GetMultiaddress() []byte {
	if x != nil {
		return x.Multiaddress
	}
	return nil
}

type P2PMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *P2PMessage) Reset() {
	*x = P2PMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sequencer_messages_defs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P2PMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PMessage) ProtoMessage() {}

func (x *P2PMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sequencer_messages_defs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PMessage.ProtoReflect.Descriptor instead.
func (*P2PMessage) Descriptor() ([]byte, []int) {
	return file_sequencer_messages_defs_proto_rawDescGZIP(), []int{7}
}

func (x *P2PMessage) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_sequencer_messages_defs_proto protoreflect.FileDescriptor

var file_sequencer_messages_defs_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x64, 0x65, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x78, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x76,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x70, 0x72, 0x65, 0x76, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x78, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0a, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73,
	0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x18, 0x14, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x55, 0x4e, 0x49, 0x58, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x04, 0x75,
	0x6e, 0x69, 0x78, 0x42, 0x0b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x29, 0x0a, 0x13, 0x55, 0x4e, 0x49, 0x58, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x1d, 0x0a, 0x03, 0x74, 0x78, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x78, 0x52, 0x03, 0x74, 0x78,
	0x73, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x43, 0x0a, 0x1d, 0x53,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x2a, 0x0a, 0x0a, 0x50, 0x32, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x4c, 0x5a, 0x4a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6d, 0x7a,
	0x65, 0x62, 0x65, 0x64, 0x65, 0x65, 0x2f, 0x67, 0x6f, 0x6c, 0x69, 0x61, 0x74, 0x68, 0x2d, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x72, 0x2f, 0x6d, 0x76, 0x70, 0x2f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sequencer_messages_defs_proto_rawDescOnce sync.Once
	file_sequencer_messages_defs_proto_rawDescData = file_sequencer_messages_defs_proto_rawDesc
)

func file_sequencer_messages_defs_proto_rawDescGZIP() []byte {
	file_sequencer_messages_defs_proto_rawDescOnce.Do(func() {
		file_sequencer_messages_defs_proto_rawDescData = protoimpl.X.CompressGZIP(file_sequencer_messages_defs_proto_rawDescData)
	})
	return file_sequencer_messages_defs_proto_rawDescData
}

var file_sequencer_messages_defs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sequencer_messages_defs_proto_goTypes = []interface{}{
	(*Block)(nil),                         // 0: Block
	(*SequenceTx)(nil),                    // 1: SequenceTx
	(*ExpiryCondition)(nil),               // 2: ExpiryCondition
	(*UNIXExpiryCondition)(nil),           // 3: UNIXExpiryCondition
	(*GetTransactions)(nil),               // 4: GetTransactions
	(*GetSequencerInfo)(nil),              // 5: GetSequencerInfo
	(*SequencerPrimaryAdvertisement)(nil), // 6: SequencerPrimaryAdvertisement
	(*P2PMessage)(nil),                    // 7: P2PMessage
}
var file_sequencer_messages_defs_proto_depIdxs = []int32{
	1, // 0: Block.body:type_name -> SequenceTx
	2, // 1: SequenceTx.expires:type_name -> ExpiryCondition
	3, // 2: ExpiryCondition.unix:type_name -> UNIXExpiryCondition
	1, // 3: GetTransactions.txs:type_name -> SequenceTx
	0, // 4: P2PMessage.block:type_name -> Block
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sequencer_messages_defs_proto_init() }
func file_sequencer_messages_defs_proto_init() {
	if File_sequencer_messages_defs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sequencer_messages_defs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SequenceTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpiryCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UNIXExpiryCondition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSequencerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SequencerPrimaryAdvertisement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sequencer_messages_defs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P2PMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sequencer_messages_defs_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ExpiryCondition_Unix)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sequencer_messages_defs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sequencer_messages_defs_proto_goTypes,
		DependencyIndexes: file_sequencer_messages_defs_proto_depIdxs,
		MessageInfos:      file_sequencer_messages_defs_proto_msgTypes,
	}.Build()
	File_sequencer_messages_defs_proto = out.File
	file_sequencer_messages_defs_proto_rawDesc = nil
	file_sequencer_messages_defs_proto_goTypes = nil
	file_sequencer_messages_defs_proto_depIdxs = nil
}
